export interface Product {
  name: string;
  num: string;
  price: number;
  img: string;
  category: string;
  quantity: string;
  material: string;
  layers: number;
  eco: string[];
}

export const PRODUCTS: Product[] = [
  {
    "name": "Cremeseife 10 ltr. rosa Hamburg Clean",
    "num": "ZU7003CREME",
    "price": 0,
    "img": "",
    "category": "seife",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Toilettenpapier 3 lagig recycling • 250 Blatt • 2112 Rollen PALETTE",
    "num": "ZUE081",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "palette",
    "material": "recycling",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Toilettenpapier 3 lagig Zellstoff ULTRA SOFT • 250 Blatt • 1848 Rollen PALETTE",
    "num": "ZU039GOLD",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "palette",
    "material": "premium",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Papierhandtücher 1 lagig GRÜN • ECO LINE Z Falzung  24x21cm  35 g/m² • Karton",
    "num": "E016-Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "recycling",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Papierhandtücher 1 lagig GRÜN • ECO LINE Z Falzung  24x21cm  35 g/m² • Palette",
    "num": "ZUE016",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "recycling",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Papierhandtücher 2 lagig weiß ECOLINE • recycling Z Falzung  25x21cm • Karton",
    "num": "E031-Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Handtuchrollen 2 lagig Zellstoff • 100m 475 Blatt • Innenauszug + Außenabwicklung • 6 Rollen VE",
    "num": "8500Karton",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Toilettenpapier 3 lagig Zellstoff 350 Blatt ohne Plastik m. Solarenergie hergestellt 10 x 4 Rollen  PALETTE",
    "num": "ZU350",
    "price": 16.87,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 3,
    "eco": [
      "ohne-plastik"
    ]
  },
  {
    "name": "Papierhandtücher 1 lagig GRAU • ECO Z Falzung 25 x 23 cm 36 g/m² • Palette",
    "num": "ZU50490015",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "recycling",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Papierhandtücher 1 lagig GRAU • ECO Z Falzung 25 x 23 cm  36 g/m² • Karton",
    "num": "015-Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "recycling",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Papierhandtücher 1 lagig GRAU • Z Falzung ohne Plastik 25x23 cm • Palette",
    "num": "ZU50490017",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 1,
    "eco": [
      "ohne-plastik"
    ]
  },
  {
    "name": "Starterset • 1 Autocutspender Weiss • 18 Handtuchrollen 2 lagig Zellstoff 130 m",
    "num": "Starter-AUTO-5000-WE",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Toilettenpapier 3 lagig 100% Zellstoff SOFT 250 Blatt 8er -  PALETTE",
    "num": "ZU50490027-H",
    "price": 21.65,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Handdesinfektion 5 ltr. STERN HD E5",
    "num": "13702",
    "price": 0,
    "img": "",
    "category": "seife",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Papierhandtücher 1 lagig  GRAU • ECO LINE Z Falzung 24x21cm 35 g/m² • Palette",
    "num": "ZUE014",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "recycling",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Papierhandtücher 1 lagig GRAU • ECO LINE Z Falzung  24x21cm 35 g/m² • Karton",
    "num": "E014-Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "recycling",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Falthandtücher 1 lagig GRÜN • Z Falzung  24 x 21 cm • Karton",
    "num": "022-Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Handtuchpapier 1 lagig weiß • Z Falzung 24x21 cm • Karton",
    "num": "029-Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Handtuchpapier 1 lagig weiß • Z Falzung 24x21cm • Palette",
    "num": "ZU50490029",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Papierhandtücher 1 lagig hellgrau • PREMIUM Z Falzung 24x21cm • Palette",
    "num": "ZU50490017-L",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Falthandtücher 1 lagig GRÜN • Z Falzung 24 x 21 cm • Palette",
    "num": "ZU50490022",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Papierhandtücher 1 lagig Interfold • recycling Havanna 21 x 24 cm  GO CLEAN • Palette",
    "num": "ZU0200GO",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "recycling",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Papierhandtücher 1 lagig Interfold • recycling Havanna 21 x 24cm GO CLEAN • Karton",
    "num": "0200Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "recycling",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Papierhandtücher 1 lagig hellgrau • PREMIUM Z Falzung 24x21cm • Karton",
    "num": "017-L-Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Papierhandtücher C Falz 1 lagig • GRAU 25 x 31 cm •  KARTON",
    "num": "1035-Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Papierhandtücher C Falz 2 lagig • Zellstoff 25 x 31cm • KARTON",
    "num": "1045-Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Papierhandtücher 2 lagig weiß ECOLINE • recycling Z Falzung 25x21cm • Palette",
    "num": "ZUE031",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Papierhandtücher 2 lagig weiß • recycling Z Falzung 21 x 21 cm • Palette",
    "num": "ZU50490050",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Papierhandtücher 2 lagig weiß • recycling Z Falzung 25x21cm • Palette",
    "num": "ZU50490031-H",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Papierhandtücher 2 lagig weiß • recycling Z Falzung 25x21cm • Karton",
    "num": "031H-Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Papierhandtücher 2 lagig hochweiß ECOLINE • Zellstoff Z Falzung 25x21cm • Palette",
    "num": "ZUE023",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Papierhandtücher 2 lagig hochweiß ECOLINE • Zellstoff Z Faltung 25x21cm • Karton",
    "num": "E023-Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Papierhandtücher 2 lagig hochweiß Zellstoff • Z Faltzung 25x21cm • Karton",
    "num": "025H-Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Papierhandtücher 2 lagig grün recycling • Z Falzung 24 x 21 cm • Karton",
    "num": "032Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Papierhandtücher 3 lagig hochweiß • Zellstoff GOLD Z Falzung 24 x 21 cm • Palette",
    "num": "ZU5049GOLD",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "premium",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Papierhandtücher 3 lagig hochweiß • Zellstoff GOLD Z Falzung 24 x 21 cm • Karton",
    "num": "049GOLD-Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "premium",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Papierhandtücher 2 lagig schwarz Zellstoff • Z Falzung 22 x 21cm • Karton",
    "num": "1039-Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Papierhandtücher 2 lagig grün recycling • Z Falzung 24 x 21 cm • Palette",
    "num": "ZU50490032",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Papierhandtücher 2 lagig Interfold • Zellstoff  20,5 x 24 cm • Karton",
    "num": "3255-Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Papierhandtücher 2 lagig Interfold • W-Falz Zellstoff 20,3 x 32 cm • PALETTE",
    "num": "ZU2032-GO-W",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Papierhandtücher 2 lagig Interfold • Zellstoff 20,5 x 24 cm • PALETTE",
    "num": "ZU3255GO",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Papierhandtücher 2 lagig Interfold •  W-Falz Zellstoff 20,3 x 32 cm • Karton",
    "num": "2032-Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Papierhandtücher 2 lagig weiß • recycling Z Falzung 21 x 21cm • Karton",
    "num": "050-Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Papierhandtücher C Falz 1 lagig • GRAU 25 x 31 cm • PALETTE",
    "num": "ZU50491035",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Papierhandtücher C Falz 2 lagig • Zellstoff 25 x 31 cm • PALETTE",
    "num": "ZU50491045",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Toilettenpapier 2 lagig Zellstoff Super Soft • 200 Blatt • 2160 Rollen PALETTE",
    "num": "ZU50490019",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "palette",
    "material": "premium",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Papierhandtücher 2 lagig hochweiß Zellstoff • Z Falzung  25x21cm •  Palette",
    "num": "ZU50490025-H",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Papierhandtücher 2 lagig schwarz Zellstoff • Z Falzung 22 x 21cm • Palette",
    "num": "ZU50491039",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Toilettenpapier 3 lagig Zellstoff • 200 Blatt • 128 Rollen KARTON",
    "num": "036-Karton",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Jumbotoilettenpapier 2 lagig recycling 330 m • Karton",
    "num": "330-Karton-18",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "karton",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Putzrolle 2 lagig BLAU Zellstoff • 35,5 cm Breite • 1000 Abrisse •  60 Rollen PALETTE",
    "num": "ZU50490420",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Toilettenpapier 2 lagig weiß recycling 250 Blatt • 2112 Rollen Palette",
    "num": "ZU50490060-H",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "palette",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Toilettenpapier 2 lagig weiß recycling • 250 Blatt • 128 Rollen Karton",
    "num": "060H-Karton",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "karton",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Toilettenpapier 2 lagig recycling weiß • 400 Blatt • 2112 Rollen PALETTE",
    "num": "ZU50490038-H",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "palette",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Toilettenpapier 2 lagig recycling weiß • 400 Blatt • 128 Rollen Karton",
    "num": "038H-Karton",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "karton",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Toilettenpapier Einzelblatt 2 lagig Zellstoff • 9000 Blatt • KARTON",
    "num": "085-Karton",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Toilettenpapier Einzelblatt 2 lagig Zellstoff • 9000 Blatt • PALETTE",
    "num": "ZU50490085",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Toilettenpapier 3 lagig Zellstoff • 150 Blatt •  2112 Rollen PALETTE",
    "num": "ZU50490030",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Toilettenpapier 3 lagig Zellstoff • 150 Blatt • 128 Rollen KARTON",
    "num": "030-Karton",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Toilettenpapier 3 lagig Zellstoff • 200 Blatt • 2112 Rollen PALETTE",
    "num": "ZU50490036",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Toilettenpapier 3 lagig Zellstoff SUPER SOFT • 250 Blatt •  64 Rollen VE",
    "num": "024Karton",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "karton",
    "material": "premium",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Toilettenpapier 3 lagig Zellstoff Ultra Soft • 250 Blatt • 112 Rollen KARTON",
    "num": "039Karton",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "karton",
    "material": "premium",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Toilettenpapier 3 lagig recycling • 250 Blatt • 128 Rollen Karton",
    "num": "E081Karton",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "karton",
    "material": "recycling",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Toilettenpapier 3 lagig Zellstoff SOFT • 250 Blatt • 2112 Rollen PALETTE",
    "num": "ZU50490027",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Toilettenpapier 3 lagig Zellstoff SOFT • 250 Blatt • 128 Rollen KARTON",
    "num": "027Karton",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Toilettenpapier 3 lagig Zellstoff SUPER SOFT • 250 Blatt • 2112 Rollen PALETTE",
    "num": "ZU50490024",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "palette",
    "material": "premium",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Toilettenpapier 4 lagig Zellstoff Super Soft • 165 Blatt • 2112 Rollen PALETTE",
    "num": "ZU50490026",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "palette",
    "material": "premium",
    "layers": 4,
    "eco": []
  },
  {
    "name": "Toilettenpapier 4 lagig Zellstoff Super Soft • 165 Blatt • 128 Rollen Karton",
    "num": "026-Karton",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "karton",
    "material": "premium",
    "layers": 4,
    "eco": []
  },
  {
    "name": "Papierhandtuchspender für 500 Blatt weiß",
    "num": "Q489571",
    "price": 0,
    "img": "",
    "category": "spender",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Papierhandtuchspender für 500 Blatt SCHWARZ",
    "num": "892316",
    "price": 0,
    "img": "",
    "category": "spender",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "9 Rollen Ärztekrepp 2 lagig Zellstoff hochweiß • Breite 50 cm • 50 Meter • Karton",
    "num": "AR5050-Karton",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "9 Rollen Ärztekrepp 2 lagig Zellstoff hochweiß • Breite 55 cm • 50 Meter • Karton",
    "num": "AR5550-Karton",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "9 Rollen Ärzterolle 2 lagig Zellstoff hochweiß • Breite 60 cm • 50 Meter • Karton",
    "num": "AR6050-Karton",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Ärztekrepp 2 lagig Zellstoff hochweiß • Breite 50 cm • 50 Meter • 216 Rollen Palette",
    "num": "ZUAR5050",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Ärztekrepp 2 lagig Zellstoff hochweiß • Breite 55 cm • 50 Meter • 162 Rollen Palette",
    "num": "ZUAR5550",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Ärzterolle 2 lagig Zellstoff hochweiß •  Breite 60 cm • 50 Meter • 162 Rollen Palette",
    "num": "ZUAR6050",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "9 Rollen Ärztekrepp 2 lagig Zellstoff hochweiß • Breite 39 cm • 50 Meter • Karton",
    "num": "AR3950-Karton",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Ärztekrepp 2 lagig Zellstoff hochweiß • Breite 39 cm • 50 Meter • 216 Rollen PALETTE",
    "num": "ZUAR3950",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Putzpapier 3 lagig BLAU Zellstoff • 35,5cm Breite • 1000 Abrisse •  Karton",
    "num": "480Karton",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Jumbotoilettenpapier 2 lagig Zellstoff 330 m • Karton",
    "num": "295-Karton",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Jumbotoilettenpapier • MINI • 2 lagig Zellstoff 175 m • 528 Rollen • PALETTE",
    "num": "ZU50490175",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Jumbotoilettenpapier • MINI • 2 lagig Zellstoff 175 m • Karton",
    "num": "175-Karton-48",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Jumbotoilettenpapier 2 lagig Zellstoff 330 m • 294 Rollen • PALETTE",
    "num": "ZU50490295",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Jumbotoilettenpapier 2 lagig recycling 330 m • 294 Rollen • PALETTE",
    "num": "ZU50490330",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "palette",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Jumbotoilettenpapier 1 lagig recycling 570 m • 252 Rollen • PALETTE",
    "num": "ZU50490400",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "palette",
    "material": "recycling",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Jumbotoilettenpapier• MINI • 2 lagig Zellstoff 130 m • 528 Rollen • PALETTTE",
    "num": "ZU50490299",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Handtuchrollen 2 lagig NATURAL • 200m 20cm Breite • 6 Rollen VE",
    "num": "5020Karton",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "karton",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Küchenrollen 2 lagig Zellstoff •  64 Blatt Höhe 26cm • Karton",
    "num": "042Karton",
    "price": 0,
    "img": "",
    "category": "kuechenrollen",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Küchenrollen 3 lagig • ECOLINE \"Multi Size\" 90 Blatt • Palette",
    "num": "ZU50490040",
    "price": 0,
    "img": "",
    "category": "kuechenrollen",
    "quantity": "palette",
    "material": "recycling",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Küchenrollen XXL • 3 lagig Zellstoff 400 Blatt • Höhe 22cm • Palette",
    "num": "ZU50490070",
    "price": 0,
    "img": "",
    "category": "kuechenrollen",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Küchenrollen 3 lagig Zellstoff • 51 Blatt Höhe 26cm • Palette",
    "num": "ZU50490048",
    "price": 0,
    "img": "",
    "category": "kuechenrollen",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Küchenkrepp 2 lagig Zellstoff • 51 Blatt Höhe 23cm • Palette",
    "num": "ZU50490045",
    "price": 0,
    "img": "",
    "category": "kuechenrollen",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Servietten 1 lagig • 33 x 33 cm 1/4 Falz • Palette",
    "num": "ZU50490072",
    "price": 0,
    "img": "",
    "category": "servietten",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Kosmetiktücher 2 lagig • 100 Blatt in der Box • Palette",
    "num": "ZU50500010",
    "price": 0,
    "img": "",
    "category": "kosmetiktuecher",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Kosmetiktücher 3 lagig • 70 Blatt in der Box • Palette",
    "num": "ZU50500011",
    "price": 0,
    "img": "",
    "category": "kosmetiktuecher",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Kosmetiktücher 3 lagig Würfel • 60 Blatt in der Box • Palette",
    "num": "ZU50500020",
    "price": 0,
    "img": "",
    "category": "kosmetiktuecher",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Servietten 2 lagig Zellstoff • 11 x 16,5 cm 9000 Stück • Palette",
    "num": "ZU50490084",
    "price": 0,
    "img": "",
    "category": "servietten",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Autocutspender für Handtuchrollen  Weiß",
    "num": "AC15025",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Innenauszug Spender schwarz",
    "num": "AC20222",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Putzpapier 3 lagig blau Zellstoff • 35,5cm Breite • 1000 Abrisse • 35 Rollen PALETTE",
    "num": "ZU50490480",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Mikrofasertücher Standard • 40 x 40 cm •  200 Stück",
    "num": "ZU4432-HA",
    "price": 0,
    "img": "",
    "category": "sonstiges",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Putztuchrolle 2 lagig BLAU Zellstoff • 35,5 cm Breite • 1000 Abr.• Karton",
    "num": "420Karton",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Papierrolle Werkstatt 2 lagig BLAU recycling • 22 cm Breite • 1000 Abrisse • 108 Rollen PALETTE",
    "num": "ZU50490155",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "palette",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Papierrollen Werkstatt 2 lagig  BLAU recycling • 22 cm Breite • 1000 Abrisse • Karton",
    "num": "155Karton",
    "price": 0,
    "img": "",
    "category": "sonstiges",
    "quantity": "karton",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Putzpapier BLAU 2 lagig recycling • 34cm Breite • 1000 Abrisse • 60 Rollen PALETTE",
    "num": "ZU50490290L",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "palette",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Putzpapier BLAU 2 lagig recycling • 34cm Breite • 1000 Abrisse • Karton",
    "num": "290Karton",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "karton",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Putzpapier WEIß 2 lagig recycling • 22cm Breite • 1500 Abrisse • 48 Rollen PALETTE",
    "num": "ZU50497500",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "palette",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Putzpapierrolle 3 lagig BLAU recycling • 34 cm Breite • 1000 Abrisse • 35 Rollen PALETTE",
    "num": "ZU50490280L",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "palette",
    "material": "recycling",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Putzpapierrolle 3 lagig BLAU recycling • 34 cm Breite • 1000 Abrisse • Karton",
    "num": "280Karton",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "karton",
    "material": "recycling",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Putzpapier 3 lagig BLAU recycling • 37 cm Breite • 1000 Abrisse • 40 Rollen PALETTE",
    "num": "ZU50490180",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "palette",
    "material": "recycling",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Putzpapier BLAU 3 lagig recycling • 37 cm Breite • 1000 Abrisse • Karton",
    "num": "0180-Karton",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "karton",
    "material": "recycling",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Handtuchrollen 2 lagig Zellstoff • 130m 20cm Breite • 6 Rollen VE",
    "num": "5000Karton",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Handtuchrollen 2 lagig Zellstoff • 130m 20cm Breite •  240 Rollen Palette",
    "num": "ZU50495000",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Handtuchrollen 2 lagig Zellstoff STRONG • 120m 20cm Breite • 6 Rollen VE",
    "num": "6000Karton",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Handtuchrollen 2 lagig Zellstoff STRONG • 120m 20cm Breite • 240 Rollen Palette",
    "num": "ZU50496000",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Autocutspender für Handtuchrollen  Schwarz",
    "num": "AC15215",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Handtuchrollen 2 lagig NATURAL • 200m 20cm Breite • 240 Rollen Palette",
    "num": "ZU50495020",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "palette",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Handtuchrollen 2-lagig Zellstoff • 130m 20,5 cm Breite • 4,4cm Hülse • 240 Rollen PALETTE",
    "num": "ZU50493000",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Handtuchrollen 2 lagig Zellstoff • 130m 20,5 cm Breite • 4,4cm Hülse •  6 Rollen VE",
    "num": "3000Karton",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Handtuchpapierrollen 3 lagig Zellstoff • 100m 20cm Breite • 6 Rollen VE",
    "num": "1001Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Papierhandtuchrollen 3 lagig Zellstoff • 100m 20cm Breite • 300 Rollen Palette",
    "num": "ZU50501001",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Wischmop Mikrofaser • 50 cm • 50 Stück per Karton",
    "num": "ZU3350",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Wischmop Mikrofaser • 40 cm • 50 Stück per Karton",
    "num": "ZU3340",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Handtuchrollen 2 lagig Zellstoff • 120m 21,3cm Breite • 240 Rollen Palette",
    "num": "ZU50410000",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Handtuchrollen 2 lagig Zellstoff • 120m 21,3cm Breite • 6 Rollen VE",
    "num": "10000Karton",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Handtuchrollen 2 lagig Zellstoff • 143m 595 Blatt • Innenauszug + Außenabwicklung •  Palette",
    "num": "ZU50498700",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Handtuchrollen 2 lagig Zellstoff • 143m 595 Blatt • Innenauszug + Außenabwicklung • 6 Rollen VE",
    "num": "8700Karton",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Innenauszug Spender weiß",
    "num": "AC20012",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Handtuchrollen 2 lagig Zellstoff • 100m 475 Blatt • Innenauszug + Außenabwicklung • 240 Rollen Palette",
    "num": "ZU50498500",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Handtuchrollen 2 lagig recycling • 143m 650 Blatt • Innenauszug + Außenabwicklung • Palette",
    "num": "ZU50497070L",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "palette",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Handtuchrollen 2 lagig recycling • 143m 650 Blatt • Innenauszug + Außenabwicklung • 6 Rollen VE",
    "num": "7070Karton",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "karton",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Handtuchrollen 2 lagig Zellstoff blau • 143m 600 Abrisse • Innenauszug • 6 Rolle VE",
    "num": "7095Karton",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Handtuchrollen 1 lagig Zellstoff • 120m 428 Blatt • Innenauszug • 6 Rollen Karton",
    "num": "225Karton",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Handtuchrollen 1 lagig Zellstoff • 300m 1070 Blatt • Innenauszug • 6 Rollen Karton",
    "num": "220Karton",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Handtuchrollen 1 lagig Zellstoff • 120m 428 Blatt • Innenauszug • Palette",
    "num": "ZU50490225",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Handtuchrollen 1 lagig Zellstoff • 300m 1070 Blatt • Innenauszug • Palette",
    "num": "ZU50490220",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Handtuchrollen 2 lagig Zellstoff blau • 143m 600 Abrisse • Innenauszug • Palette",
    "num": "ZU50497095",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Handtuchrollen 1 lagig Zellstoff • 275m Breite 19cm • Innenauszug + Außenabwicklung • 6 Rollen VE",
    "num": "8080Karton",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Handtuchrollen 1 lagig Zellstoff • 275m Breite 19cm • Innenauszug + Außenabwicklung • Palette",
    "num": "ZU50498080",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Papierhandtücher 1 lagig GRAU • Z Falzung ohne Plastik 25x23 cm • Karton",
    "num": "017Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 1,
    "eco": [
      "ohne-plastik"
    ]
  },
  {
    "name": "Jumbotoilettenpapier 1 lagig recycling 570 m • Karton",
    "num": "400-Karton",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "karton",
    "material": "recycling",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Küchenrollen 3 lagig Zellstoff • 51 Blatt Höhe 26cm • Karton",
    "num": "048Karton",
    "price": 0,
    "img": "",
    "category": "kuechenrollen",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Küchenrollen 3 lagig • ECOLINE \"Multi Size\" 90 Blatt • Karton",
    "num": "040Karton",
    "price": 0,
    "img": "",
    "category": "kuechenrollen",
    "quantity": "karton",
    "material": "recycling",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Küchenrollen XXL • 3 lagig Zellstoff 400 Blatt • Höhe 22cm • Karton",
    "num": "070Karton",
    "price": 0,
    "img": "",
    "category": "kuechenrollen",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Küchenrollen 2 lagig Zellstoff • 64 Blatt Höhe 26cm • Palette",
    "num": "ZU50490042",
    "price": 0,
    "img": "",
    "category": "kuechenrollen",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Servietten 1 lagig • 33 x 33 cm 1/4 Falz • Karton",
    "num": "072Karton",
    "price": 0,
    "img": "",
    "category": "servietten",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 1,
    "eco": []
  },
  {
    "name": "Servietten 2 lagig recycling • 11 x 16,5 cm 9000 Stück • Karton",
    "num": "043Karton",
    "price": 0,
    "img": "",
    "category": "servietten",
    "quantity": "karton",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Servietten 2 lagig Zellstoff • 11 x 16,5 cm 9000 Stück • Karton",
    "num": "084Karton",
    "price": 0,
    "img": "",
    "category": "servietten",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Servietten 2 lagig recycling • 11 x 16,5 cm 9000 Stück • Palette",
    "num": "ZU50490043",
    "price": 0,
    "img": "",
    "category": "servietten",
    "quantity": "palette",
    "material": "recycling",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Serviettenspender weiss ABS mit antibakterieller Oberfäche",
    "num": "Q492967",
    "price": 0,
    "img": "",
    "category": "spender",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Kosmetiktücher 2 lagig • 100 Blatt in der Box • Karton",
    "num": "010Karton",
    "price": 0,
    "img": "",
    "category": "kosmetiktuecher",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Kosmetiktücher 3 lagig Würfelbox • 60 Blatt in der Box • Karton",
    "num": "020Karton",
    "price": 0,
    "img": "",
    "category": "kosmetiktuecher",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Kosmetiktücher 3 lagig • 70 Blatt in der Box • Karton",
    "num": "011Karton",
    "price": 0,
    "img": "",
    "category": "kosmetiktuecher",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Seifenspender wiederbefüllbar • 1000 ml • schwarz",
    "num": "Q11232",
    "price": 0,
    "img": "",
    "category": "spender",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Seifenspender wiederbefüllbar • 1000 ml • Weiß",
    "num": "Q489570",
    "price": 0,
    "img": "",
    "category": "spender",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Toilettenpapierspender für 2 Rollen • Weiß",
    "num": "Q489574W",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Schaumseifenkonzentrat • 800ml • 6 Patronen",
    "num": "Q489590",
    "price": 0,
    "img": "",
    "category": "seife",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Schaumseifenspender • 800ml • Weiß",
    "num": "Q489585W",
    "price": 0,
    "img": "",
    "category": "spender",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Jumbotoilettenpapier Spender weiß • Ø 30cm",
    "num": "AC22012",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Papierhandtuchspender für 500 Blatt  INTERFOLD weiß",
    "num": "AC17012",
    "price": 0,
    "img": "",
    "category": "spender",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Starterset • 1 Autocutspender schwarz • 18 Handtuchrollen 2 lagig Zellstoff 130 m",
    "num": "Starter-AUTO-5000-SW",
    "price": 0,
    "img": "",
    "category": "handtuchrollen",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 2,
    "eco": []
  },
  {
    "name": "Toilettenpapierspender für 2 Rollen • Schwarz",
    "num": "Q489574S",
    "price": 0,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Schaumseifenspender • 800ml • Schwarz",
    "num": "Q489585S",
    "price": 0,
    "img": "",
    "category": "spender",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Mikrofasertücher Standard • 40 x 40 cm • Stück",
    "num": "HK4430-HA",
    "price": 0,
    "img": "",
    "category": "sonstiges",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Jumborollen Spender schwarz • Ø 30cm",
    "num": "AC22222",
    "price": 0,
    "img": "",
    "category": "spender",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Jumborollen Spender schwarz • Ø 30cm",
    "num": "AC22222-ALT",
    "price": 0,
    "img": "",
    "category": "spender",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Papierhandtücher 1 lagig GRAU • Z Falzung ohne Plastik 25x23 cm • Karton",
    "num": "017-Karton",
    "price": 0,
    "img": "",
    "category": "papierhandtuecher",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 1,
    "eco": [
      "ohne-plastik"
    ]
  },
  {
    "name": "Müllsack DEISS PREMIUN PLUS 120 ltr. blau 10 Rollen x 25 Stück im Karton",
    "num": "ZU20013",
    "price": 0,
    "img": "",
    "category": "sonstiges",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Mikrofasertuch Standard 40x40cm - 200 Stück PALETTE",
    "num": "ZU4432-HP",
    "price": 67.65,
    "img": "",
    "category": "putzpapier",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Mikrofasertuch Blau 40x40cm Standard - 250 Stück per Karton",
    "num": "ZU4432-250",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Mikrofasertuch Rot 40x40cm Standard - 250 Stück per Karton",
    "num": "ZU4433-250",
    "price": 0,
    "img": "",
    "category": "putzpapier",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Mikrofasertücher Rot 40x40cm PREMIUM - 250 Stück per Karton",
    "num": "ZU3005",
    "price": 69.61,
    "img": "",
    "category": "sonstiges",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Mikrofasertücher Blau 40x40cm PREMIUM - 250 Stück per Karton",
    "num": "ZU3010",
    "price": 68.43,
    "img": "",
    "category": "sonstiges",
    "quantity": "karton",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Putzpapier 3 lagig blau Zellstoff 132m  550 Blatt ohne Hülse  Palette",
    "num": "ZU50497080",
    "price": 23.32,
    "img": "",
    "category": "putzpapier",
    "quantity": "palette",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Mikrofasertuch Standard 40x40cm  MUSTER",
    "num": "ZU4432-MUS-HA",
    "price": 0.01,
    "img": "",
    "category": "putzpapier",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 0,
    "eco": []
  },
  {
    "name": "Kosmetiktücher 3 lagig  Muster",
    "num": "011Muster",
    "price": 0.01,
    "img": "",
    "category": "kosmetiktuecher",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Kosmetiktücher 3 lagig CUBE  Muster",
    "num": "020Muster",
    "price": 0.01,
    "img": "",
    "category": "kosmetiktuecher",
    "quantity": "stueck",
    "material": "zellstoff",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Toilettenpapier 3 lagig 100% recycling  250 Blatt 8er 2112 Rollen",
    "num": "SE50490081",
    "price": 17.96,
    "img": "",
    "category": "toilettenpapier",
    "quantity": "stueck",
    "material": "recycling",
    "layers": 3,
    "eco": []
  },
  {
    "name": "Servietten 100% recycling 2 lagig 11 x 16,5cm  GO CLEAN  Muster",
    "num": "043MUSTER",
    "price": 0.01,
    "img": "",
    "category": "servietten",
    "quantity": "stueck",
    "material": "recycling",
    "layers": 2,
    "eco": []
  }
];
